---
# - hosts: all
- name: Shutdown cluster
  hosts: localhost
  connection: local
  tasks:
  - name: shutdown nodes
#     shell: |
#     for node in $(oc get nodes -o jsonpath='{.items[*].metadata.name}'); do oc debug node/${node} -- chroot /host shutdown -h 1; done
    shell: /usr/bin/uptime
    register: uptime
  - debug: msg="{{uptime.stdout_lines}}"
   
